from flask import Blueprint, jsonify, request
from flask_jwt_extended import jwt_required, get_jwt_identity
from app.models import QuizQuestion, GameHistory, User, CoinTransaction, Scenario
from sqlalchemy import func
from app import db

quiz_bp = Blueprint('quiz', __name__)



@quiz_bp.route('/start', methods=['GET'])
@jwt_required() 
def start_quiz():
    """Fetches 6 random questions based on topic and difficulty."""
    topic = request.args.get('topic')
    difficulty = request.args.get('difficulty', default=1, type=int)

    if not topic:
        return jsonify({"msg": "Topic is required"}), 400

    questions = QuizQuestion.query.filter_by(
        topic=topic, 
        difficulty_level=difficulty
    ).order_by(func.random()).limit(6).all()
    
    if not questions:
        return jsonify({"msg": f"No questions found for {topic} at difficulty {difficulty}"}), 404
    
    quiz_data = []
    for q in questions:
        quiz_data.append({
            "id": q.question_id,
            "question": q.question_text,
            "options": {
                "A": q.option_a,
                "B": q.option_b,
                "C": q.option_c,
                "D": q.option_d
            },
            "answer": q.correct_answer 
        })
    
    return jsonify(quiz_data), 200

@quiz_bp.route('/submit', methods=['POST'])
@jwt_required()
def submit_quiz():
    """Processes quiz completion and saves the snapshot for review."""
    user_id = get_jwt_identity()
    data = request.get_json()
    
    user = User.query.get(user_id)
    if not user:
        return jsonify({"msg": "User not found"}), 404
        
    old_level = user.level 
    
    quiz_snapshot = data.get('quiz_snapshot', [])
    # Guard against zero attempts to prevent crash
    total_attempts = data.get('total_attempts', 6)
    if total_attempts == 0: total_attempts = 6 
    
    xp_reward = data.get('xp_reward', 50)
    
    # Calculate accuracy
    accuracy = (6 / total_attempts) * 100
    coin_reward = 100 
    
    # Update User Profile - Using xp_total to match your model fix
    user.coin_balance += coin_reward
    user.xp_total += xp_reward
    
    new_transaction = CoinTransaction(
        user_id=user_id,
        amount=coin_reward,
        activity_type='Quiz'
    )
    
    history = GameHistory(
        user_id=user_id,
        game_type="Quiz",
        score=accuracy,
        quiz_snapshot=quiz_snapshot
    )
    
    db.session.add(new_transaction)
    db.session.add(history)
    
    # Commit first so history.history_id is generated by the DB
    db.session.commit()
    
    return jsonify({
        "msg": "Quiz complete!",
        "history_id": history.history_id, 
        "xp_gained": xp_reward,
        "coins_earned": coin_reward,
        "new_xp_total": user.xp_total,
        "current_level": user.level, # Now safe because user.py is fixed!
        "leveled_up": user.level > old_level,
        "accuracy": round(accuracy, 2)
    }), 200

@quiz_bp.route('/review/<int:history_id>', methods=['GET'])
@jwt_required()
def get_quiz_review(history_id):
    """
    Requirement: Fetch a specific quiz session's snapshot for the review screen.
    """
    current_user_id = get_jwt_identity()
    
    # Ensure the history record exists and belongs to the logged-in user
    history = GameHistory.query.filter_by(
        history_id=history_id, 
        user_id=current_user_id
    ).first()

    if not history:
        return jsonify({"msg": "Review data not found"}), 404

    if not history.quiz_snapshot:
        return jsonify({"msg": "No snapshot available for this session"}), 400

    return jsonify({
        "game_type": history.game_type,
        "score": float(history.score),
        # Removed "completed_at" to match the model in game.py
        "questions": history.quiz_snapshot 
    }), 200

@quiz_bp.route('/history', methods=['GET'])
@jwt_required()
def get_user_history():
    current_user_id = get_jwt_identity()
    history = GameHistory.query.filter_by(user_id=current_user_id).all()
    
    results = []
    for h in history:
        # Check if quiz_snapshot exists and is a list with at least one item
        topic_name = "Unknown"
        if h.quiz_snapshot and isinstance(h.quiz_snapshot, list) and len(h.quiz_snapshot) > 0:
            # Use .get() so it returns None instead of crashing if 'topic' is missing
            topic_name = h.quiz_snapshot[0].get('topic', "Unknown")
            
        results.append({
            "game_type": h.game_type,
            "topic": topic_name,
            "score": float(h.score)
        })
    
    return jsonify(results), 200

@quiz_bp.route('/scenario/<int:scenario_id>', methods=['GET'])
@jwt_required()
def get_scenario(scenario_id):
    scenario = Scenario.query.get_or_404(scenario_id)
    return jsonify(scenario.to_dict())

@quiz_bp.route('/scenario/next', methods=['GET'])
@jwt_required()
def get_next_scenario():
    user_id = get_jwt_identity()
    user = User.query.get(user_id)
    
    # Get IDs of scenarios this user has already finished
    completed_ids = [s.id for s in user.completed_scenarios]
    
    # Find the first scenario NOT in that list, ordered by scenario_id
    next_scenario = Scenario.query.filter(~Scenario.id.in_(completed_ids))\
        .order_by(Scenario.scenario_id.asc()).first()
    
    if not next_scenario:
        return jsonify({"msg": "All scenarios completed!", "finished": True}), 200
        
    return jsonify(next_scenario.to_dict()), 200

@quiz_bp.route('/scenario/submit', methods=['POST'])
@jwt_required()
def submit_scenario():
    user_id = get_jwt_identity()
    data = request.get_json()
    is_correct = data.get('is_correct')
    
    scenario = Scenario.query.get_or_404(data.get('id'))
    user = User.query.get(user_id)

    xp_earned = 0
    coins_earned = 0

    if is_correct:
        xp_earned = 50
        coins_earned = 100
        user.xp_total += xp_earned
        user.coin_balance += coins_earned
        
        if scenario not in user.completed_scenarios:
            user.completed_scenarios.append(scenario)
        
        db.session.commit()

    return jsonify({
        "is_correct": is_correct,
        "feedback": scenario.feedback.get(data.get('choice')),
        "lesson": scenario.lesson,
        "xp_earned": xp_earned,
        "coins_earned": coins_earned
    })